/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.newpi.as;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import static javax.swing.text.html.HTML.Tag.TD;

/**
 *
 * @author Proyecto
 */
public class Interfaz_menu extends javax.swing.JFrame {

    String cad1,cad2,cad3,cad4,cad5,cad6;
    boolean modificando=false;
    boolean insertar_presionado=false;
    
    TablaEmpleado TE = new TablaEmpleado();
    TablaDoctor TD = new TablaDoctor();
    TablaHospitacizacion TH = new TablaHospitacizacion();
    TablaHabitacion TB=new TablaHabitacion();
    TablaPaciente TP=new TablaPaciente();
    
    /**
     * Creates new form Interfaz_menu
     */
    public Interfaz_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmpleadoNumero = new javax.swing.JTextField();
        txtEmpleadoNombre = new javax.swing.JTextField();
        txtEmpleadoApellido = new javax.swing.JTextField();
        txtEmpleadoDireccion = new javax.swing.JTextField();
        txtEmpleadoTelefono = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtDoctorEspecialidad = new javax.swing.JTextField();
        txtDoctorNumero = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtHospitalizacionNumero = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtHospitalizacionServicio = new javax.swing.JTextField();
        txtHospitalizacionCama = new javax.swing.JTextField();
        txtHospitalizacionHabitacion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtHabitacionNumero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtHabitacionSupervisor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtHabitacionServicio = new javax.swing.JTextField();
        txtHabitacionCama = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txtPacienteNumero = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtPacienteNombre = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtPacienteApellido = new javax.swing.JTextField();
        txtPacienteDireccion = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtPacienteTelefono = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtPacienteSuguro = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnCosultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        Table_dinamic = new javax.swing.JScrollPane();
        TableDinamic = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gestor de Hospital");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel3.setEnabled(false);

        jLabel2.setText("Numero:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Dirección:");

        jLabel6.setText("Telefono:");

        txtEmpleadoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpleadoApellidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpleadoNombre))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpleadoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpleadoDireccion))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmpleadoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtEmpleadoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtEmpleadoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpleadoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpleadoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtEmpleadoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpleadoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empleado", jPanel3);

        jPanel5.setEnabled(false);

        jLabel21.setText("Numero:");

        jLabel22.setText("Especialidad");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(txtDoctorEspecialidad))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(35, 35, 35)
                        .addComponent(txtDoctorNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtDoctorNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtDoctorEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Doctor", jPanel5);

        jPanel4.setEnabled(false);

        jLabel17.setText("Numero de paciente:");

        jLabel18.setText("Codigo de servicio:");

        txtHospitalizacionHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalizacionHabitacionActionPerformed(evt);
            }
        });

        jLabel19.setText("Numero de habitacion:");

        jLabel20.setText("Numero de cama:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHospitalizacionServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(txtHospitalizacionNumero))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHospitalizacionCama, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(txtHospitalizacionHabitacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(txtHospitalizacionNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospitalizacionHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(txtHospitalizacionServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospitalizacionCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hospitalizacion", jPanel4);

        jPanel6.setEnabled(false);

        jLabel12.setText("Numero de habitacion:");

        jLabel13.setText("Supervisor:");

        jLabel14.setText("Numero de Cama:");

        jLabel15.setText("Codigo de servicio:");

        txtHabitacionServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHabitacionServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHabitacionSupervisor))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHabitacionNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHabitacionCama))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHabitacionServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(txtHabitacionNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHabitacionServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(txtHabitacionSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHabitacionCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Habitacion", jPanel6);

        jPanel7.setEnabled(false);

        jLabel23.setText("Numero:");

        jLabel24.setText("Nombre:");

        jLabel25.setText("Dirección:");

        jLabel26.setText("Apellido:");

        txtPacienteApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteApellidoActionPerformed(evt);
            }
        });

        jLabel27.setText("Telefono:");

        jLabel28.setText("Seguro:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPacienteNombre))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPacienteNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPacienteDireccion))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPacienteApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPacienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPacienteSuguro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(txtPacienteNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPacienteApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPacienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(txtPacienteSuguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel25)
                        .addComponent(txtPacienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPacienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Paciente", jPanel7);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnCosultar.setText("Consultar");
        btnCosultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosultarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        TableDinamic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_dinamic.setViewportView(TableDinamic);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(Table_dinamic, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCosultar, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addGap(27, 27, 27)
                        .addComponent(btnCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addComponent(btnInsertar))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCosultar)
                    .addComponent(btnModificar)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Table_dinamic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpleadoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpleadoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpleadoApellidoActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
       // habilitar_empleado(true);
        selec_tab(txtEmpleadoNumero, txtHospitalizacionNumero, txtDoctorNumero);
        insertar_presionado=true;
            switch(jTabbedPane1.getSelectedIndex()){
            case 0:

                String num = txtEmpleadoNumero.getText();
                String nom = txtEmpleadoNombre.getText();
                String ape = txtEmpleadoApellido.getText();
                String dir = txtEmpleadoDireccion.getText();
                String tel = txtEmpleadoTelefono.getText();
                try {
                    if (!modificando) {
                        new Conexion().exec(
                               "insert into employe(numero, nom, prenom, adresse, tel) "
                               + "values(" + num + ", '" + nom + "', '"
                                          + ape + "', '" + dir + "', '" + tel + "')");
                        
                    } else {
                        String cmd = String.format(
                                "update employe set "
                                + "numero=%s, nom='%s', prenom='%s', adresse='%s', tel='%s'"
                                + " where "
                                + "numero=%s and nom='%s' and prenom='%s' and adresse='%s' and tel='%s'",
                                num, nom, ape, dir, tel, cad1, cad2, cad3, cad4, cad5);

                        new Conexion().exec(cmd);
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    ex.printStackTrace();
                }
                habilitar(false);
                break;
            case 1:
                String numero = txtDoctorNumero.getText();
                String especialidad = txtDoctorEspecialidad.getText();
                try {
                    if (!modificando) {
                        new Conexion().exec(
                               "insert into docteur(numero, specialite) "
                               + "values(" + numero + ", '" + especialidad +  "')");
                    } else {
                        String cmd = String.format(
                                "update docteur set "
                                + "numero=%s, specialite='%s'"
                                + " where "
                                + "numero=%s and specialite='%s'",
                                numero, especialidad, cad1, cad2);

                        new Conexion().exec(cmd);
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    ex.printStackTrace();
                }
                habilitar(false);
                
                break;
                            
            case 2:
                String nPacientes = txtHospitalizacionNumero.getText();
                String servicios = txtHospitalizacionServicio.getText();
                String nCama = txtHospitalizacionCama.getText();
                String habitacion = txtHospitalizacionHabitacion.getText();
                try {
                    if (!modificando) {
                        new Conexion().exec(
                               "insert into hospitalisation(no_malade, code_service, no_chambre, lit) "
                               + "values(" + nPacientes + ", '" + servicios + "', "
                                          + habitacion + ", " + nCama +")");
                    } else {
                        String cmd = String.format(
                                "update hospitalisation set "
                                + "no_malade=%s, code_service='%s', no_chambre=%s, lit=%s "
                                + " where "
                                + "no_malade=%s and code_service='%s' and no_chambre=%s and lit=%s ",
                                nPacientes, servicios, habitacion, nCama, cad1, cad2, cad3, cad4);

                        new Conexion().exec(cmd);
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    ex.printStackTrace();
                }
                habilitar(false);
                break;
            case 3:
                String nHabitacion = txtHabitacionNumero.getText();
                String supervisor = txtHabitacionSupervisor.getText();
                String codServicio = txtHabitacionServicio.getText();
                String numCama = txtHabitacionCama.getText();
                try {
                    if (!modificando) {
                        new Conexion().exec(
                               "insert into chambre(code_service, no_chambre, surveillant, nb_lits) "
                               + "values(" + codServicio + ", '" + nHabitacion + "', '"
                                          + supervisor + "', '" + numCama +"')");
                    } else {
                        String cmd = String.format(
                                "update chambre set "
                                + "code_service='%s', no_chambre=%s, surveillant=%s, nb_lits=%s "
                                + " where "
                                + "code_service='%s' and no_chambre='%s' and surveillant=%s and nb_lits=%s ",
                                codServicio, nHabitacion, supervisor, numCama, cad1, cad2, cad3, cad4);

                        new Conexion().exec(cmd);
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    ex.printStackTrace();
                }
                habilitar(false);
                break;
            case 4:
                String pnum = txtPacienteNumero.getText();
                String pnom = txtPacienteNombre.getText();
                String pape = txtPacienteApellido.getText();
                String pdir = txtPacienteDireccion.getText();
                String ptel = txtPacienteTelefono.getText();
                String seguro = txtPacienteSuguro.getText();
                try {
                    if (!modificando) {
                        new Conexion().exec(
                               "insert into malade(numero, nom, prenom, adresse, tel, mutuelle) "
                               + "values(" + pnum + ", '" + pnom + "', '"
                                          + pape + "', '" + pdir + "', '" + ptel + "', '"+ seguro + "')");
                    } else {
                        String cmd = String.format(
                                "update malade set "
                                + "numero=%s, nom='%s', prenom='%s', adresse='%s', tel='%s', seguro='%s'"
                                + " where "
                                + "numero=%s and nom='%s' and prenom='%s' and adresse='%s' and tel='%s' and seguro='%s'",
                                pnum, pnom, pape, pdir, ptel, seguro, cad1, cad2, cad3, cad4, cad5, cad6);

                        new Conexion().exec(cmd);
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    ex.printStackTrace();
                }
                habilitar(false);
                break;
                        
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtHospitalizacionHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalizacionHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalizacionHabitacionActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        // TODO add your handling code here:
        String num=txtEmpleadoNumero.getText();
        String nom=txtEmpleadoNombre.getText();
        String ape=txtEmpleadoApellido.getText();
        String dir=txtEmpleadoDireccion.getText();
        String tel=txtEmpleadoTelefono.getText();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
       /* System.out.println(jTabbedPane1.getSelectedIndex());
        switch (jTabbedPane1.getSelectedIndex()) {
            case 0: txtEmpleadoNumero.grabFocus(); break;
            case 1: txtHospitalizacionNumero.grabFocus(); break;
            case 2: txtDoctorNumero.grabFocus(); break;
        }*/
        // TODO add your handling code here:
        if(insertar_presionado==false)
        {
            selec_tab(txtEmpleadoNumero, txtHospitalizacionNumero, txtDoctorNumero);
            
        }
        switch(jTabbedPane1.getSelectedIndex()){
            case 0:
                TableDinamic.setModel(TE);
                break;
            case 1:
                TableDinamic.setModel((TableModel)TD);
                break;
            case 2:
                TableDinamic.setModel((TableModel)TH);
                break;
            case 3:
                TableDinamic.setModel((TableModel)TB);
                break;
            case 4:
                TableDinamic.setModel((TableModel)TP);
                break;
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
        switch(jTabbedPane1.getSelectedIndex())
        {
            case 0:

                String num = txtEmpleadoNumero.getText();
                String nom = txtEmpleadoNombre.getText();
                String ape = txtEmpleadoApellido.getText();
                String dir = txtEmpleadoDireccion.getText();
                String tel = txtEmpleadoTelefono.getText();
                try {
                    if (!modificando) {
                        new Conexion().execQueri("update employe set "
                                + "numero=%s, nom='%s', prenom='%s', adresse='%s', tel='%s'"
                                + " where "
                                + "numero=%s and nom='%s' and prenom='%s' and adresse='%s' and tel='%s'",
                                num, nom, ape, dir, tel, cad1, cad2, cad3, cad4, cad5);
                        
                    } 
                } catch (ClassNotFoundException | SQLException ex) {
                    ex.printStackTrace();
                }
                habilitar(false);
                break;
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtHabitacionServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHabitacionServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHabitacionServicioActionPerformed

    private void txtPacienteApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteApellidoActionPerformed

    private void btnCosultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosultarActionPerformed
         // TODO add your handling code here:
         switch(jTabbedPane1.getSelectedIndex()){
            case 0:

                String num = txtEmpleadoNumero.getText();
                String nom = txtEmpleadoNombre.getText();
                String ape = txtEmpleadoApellido.getText();
                String dir = txtEmpleadoDireccion.getText();
                String tel = txtEmpleadoTelefono.getText();
                try {
                        new Conexion().execQueri("select * FROM employe "
                                + "numero=%s, nom='%s', prenom='%s', adresse='%s', tel='%s'"
                                + " where "
                                + "numero=%s and nom='%s' and prenom='%s' and adresse='%s' and tel='%s'",
                                num, nom, ape, dir, tel, cad1, cad2, cad3, cad4, cad5);
                               
                } catch (ClassNotFoundException | SQLException ex) {
                    ex.printStackTrace();
                }
                habilitar(false);
                break;
         }
    }//GEN-LAST:event_btnCosultarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        switch(jTabbedPane1.getSelectedIndex()){
        
        }
        String num = txtEmpleadoNumero.getText();
        String nom = txtEmpleadoNombre.getText();
        String ape = txtEmpleadoApellido.getText();
        String dir = txtEmpleadoDireccion.getText();
        String tel = txtEmpleadoTelefono.getText();                
        String cmd = String.format(
                "delete from employe where  "
                + "numero=%s and nom='%s' and prenom='%s' and adresse='%s' and tel='%s'",
                num, nom, ape, dir, tel);
        try {
            if (JOptionPane.showConfirmDialog(
                    this,
                    "Está seguro?",
                    "Sure?", 
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                new Conexion().exec(cmd);

            }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_menu().setVisible(true);
            }
        });
    }
    
//    private void habilitar_empleado(boolean e,int opc)
//    {
//        switch(opc)
//        {
//            case 0:
//                btnAceptar.setEnabled(e);
//                btnCancelar.setEnabled(e);
//                btnInsertar.setEnabled(!e);
//                btnEliminar.setEnabled(!e);
//                btnModificar.setEnabled(!e);
//                btnCosultar.setEnabled(!e);
//                txtEmpleadoNombre.setEditable(e);
//                txtEmpleadoApellido.setEditable(e);
//                txtEmpleadoDireccion.setEditable(e);
//                txtEmpleadoTelefono.setEditable(e);
//                txtEmpleadoNumero.setEditable(e);
//            break;
//            
//            case 1:
//                
//            break;
//                
//        }
//            
//        
//    }
    
    
    private void habilitar(boolean estado) {
        btnAceptar.setEnabled(estado);
        btnCancelar.setEnabled(estado);
        btnInsertar.setEnabled(!estado);
        btnEliminar.setEnabled(!estado);
        btnModificar.setEnabled(!estado);
        
        switch(jTabbedPane1.getSelectedIndex()){
            case 0:         
                txtEmpleadoNombre.setEditable(estado);
                txtEmpleadoNombre.setEditable(estado);
                txtEmpleadoApellido.setEditable(estado);
                txtEmpleadoTelefono.setEditable(estado);
                txtEmpleadoTelefono.setEditable(estado);
                break;
                
            case 1:
                txtDoctorNumero.setEditable(estado);
                txtDoctorEspecialidad.setEditable(estado);
                break;
            case 2:
//                txtHabitacionCodServ.setEditable(estado);
//                txtHabitacionNumCama.setEditable(estado);
//                txtHabitacionNumHabitacion.setEditable(estado);
//                txtHabitacionSupervisor.setEditable(estado);
                break;
        }
    }
    
    /*private void limpiar()
    {
        ArrayList<JTextField> espacios=new ArrayList<>();
        for(int i=0;i<(11);i++)
        {
            espacios.add(i,jPanel1.);
        }
    }*/
    
    
    
    private void selec_tab(JTextField a,JTextField b,JTextField c)
    {
        switch(jTabbedPane1.getSelectedIndex())
        {
            case 0: 
                a.grabFocus();
                jPanel3.setEnabled(false);
            break;
            case 1: 
                b.grabFocus();
                jPanel4.setEnabled(false);
            break;
            case 2: 
                c.grabFocus();
                jPanel5.setEnabled(false);
            break;            
       }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDinamic;
    private javax.swing.JScrollPane Table_dinamic;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCosultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtDoctorEspecialidad;
    private javax.swing.JTextField txtDoctorNumero;
    private javax.swing.JTextField txtEmpleadoApellido;
    private javax.swing.JTextField txtEmpleadoDireccion;
    private javax.swing.JTextField txtEmpleadoNombre;
    private javax.swing.JTextField txtEmpleadoNumero;
    private javax.swing.JTextField txtEmpleadoTelefono;
    private javax.swing.JTextField txtHabitacionCama;
    private javax.swing.JTextField txtHabitacionNumero;
    private javax.swing.JTextField txtHabitacionServicio;
    private javax.swing.JTextField txtHabitacionSupervisor;
    private javax.swing.JTextField txtHospitalizacionCama;
    private javax.swing.JTextField txtHospitalizacionHabitacion;
    private javax.swing.JTextField txtHospitalizacionNumero;
    private javax.swing.JTextField txtHospitalizacionServicio;
    private javax.swing.JTextField txtPacienteApellido;
    private javax.swing.JTextField txtPacienteDireccion;
    private javax.swing.JTextField txtPacienteNombre;
    private javax.swing.JTextField txtPacienteNumero;
    private javax.swing.JTextField txtPacienteSuguro;
    private javax.swing.JTextField txtPacienteTelefono;
    // End of variables declaration//GEN-END:variables
}
